services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    # To expose the port to the host system, uncomment the lines below.
    # Change the port number before the colon (5432) to whatever port you want.
    # ports:
    #   - 5432:5432
    networks:
      - proxy-net

  postgrest:
    image: postgrest/postgrest:v12.0.2
    container_name: postgrest
    restart: unless-stopped
    environment:
      PGRST_DB_URI: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      PGRST_DB_SCHEMA: ${PGRST_DB_SCHEMA}
      PGRST_DB_ANON_ROLE: ${PGRST_DB_ANON_ROLE}
    depends_on:
      - postgres
    # To expose the port to the host system, uncomment the lines below.
    # Change the port number before the colon (3000) to whatever port you want.
    # ports:
    #   - 3000:3000
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true
